name: n0name
version: '0.1'
summary: A better Reader on macOS and Linux. Built with Electron.
description: |
    better Reader with color highlight

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  n0name:
    # command: desktop-launch $SNAP/n0name.wrapper
    command: npm start
    plugs:
      - unity7
      - opengl
      - network
      - home
      - browser-support
      - gsettings
      - x11
      - pulseaudio
      - alsa

parts:
  n0name:
    plugin: nodejs
    source-type: git
    source: https://github.com/ciiiii/snap-electron-reader
    source-branch: master
    node-packages:
      - electron
    stage-packages:
      - libnss3
      - fontconfig-config
      - gnome-themes-standard
      - fonts-wqy-microhei
